import type { Metadata } from "next"
import { Poppins } from "next/font/google"

// ** Custom Componenst
import Header from "@/components/page/Header"
import Footer from "@/components/page/Footer"

// ** Context
import { SidebarProvider } from "@/context/SidebarContext"
import { TimerSettingProvider } from "@/context/TimerSettingContext"

import "./globals.scss"

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <SidebarProvider>
        <TimerSettingProvider>
          <body className={poppins.className}>
            <main className={`overflow-hidden bg-[#F1F1F1]`}>
              <Header />
              {children}
              <Footer />
            </main>
          </body>
        </TimerSettingProvider>
      </SidebarProvider>
    </html>
  )
}
